### ISSUE TITLE
Bug: ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by tryallthethings** [pilky/twitchmata#53]
**Describe the bug**
I'm currently trying to get an overlay running in Unity using Twitchmata. While doing so I noticed an error in the Unity Console:

```
ArgumentNullException: Value cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <27586baf39bf4babbfd8a2caabe8e228>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].ContainsKey (TKey key) (at <27586baf39bf4babbfd8a2caabe8e228>:0)
Twitchmata.UserManager.UserWithID (System.String userID) (at Assets/External/Twitchmata/UserManager.cs:28)
Twitchmata.UserManager.ExistingOrNewUser (System.String userID, System.String userName, System.String displayName) (at Assets/External/Twitchmata/UserManager.cs:98)
Twitchmata.UserManager.UserForSubscriptionNotification (TwitchLib.PubSub.Models.Responses.Messages.ChannelSubscription subscriptionNotification) (at Assets/External/Twitchmata/UserManager.cs:135)
Twitchmata.SubscriberManager.PubSub_OnChannelSubscription (System.Object sender, TwitchLib.PubSub.Events.OnChannelSubscriptionArgs arg) (at Assets/External/Twitchmata/FeatureManagers/SubscriberManager.cs:153)
TwitchLib.Unity.PubSub+<>c__DisplayClass111_21.<.ctor>b__58 () (at <5a6d6e98208f4e00995c90390ef1878d>:0)
TwitchLib.Unity.ThreadDispatcher.Update () (at <5a6d6e98208f4e00995c90390ef1878d>:0)
```
Time-wise, this happened at the moment a viewer was gifted a subscription. My code for handling the new subscriber is this:

```
	public override void UserSubscribed(Twitchmata.Models.User subscriber)
	{
		if (subscriber.Subscription.IsGift == true)
		{
			Debug.Log($"{subscriber.DisplayName} received gift sub from {subscriber.Subscription.Gifter.DisplayName}");
		}
		else
		{
			Debug.Log($"{subscriber.DisplayName} subscribed. They have subscribed for {subscriber.Subscription.SubscribedMonthCount}");
		}
		_twitchTracker.AddSubscription();
		this.Manager.Utilities.FetchAvatarForUserAsTexture(subscriber, (texture) => {
			Debug.Log("Trying to get user image");
			userProfilePic.texture = texture;
			//Save_Texture2D(texture, @"D:\" + subscriber.DisplayName.ToString() + ".png");
		});
	}
```
The `Debug.Log($"{subscriber.DisplayName} received gift sub from {subscriber.Subscription.Gifter.DisplayName}");` isn't showing up in the log, so I suppose it's the event itself causing the issue. `_twitchTracker.AddSubscription();` wasn't called either.

I've only seen this issue once so far. So I don't have any steps to reproduce. But I can tell you that subs / gift subs before and after the error were working just fine.

**Expected behavior**
No exception would be great :D

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - Unity Version 2022.2.12f1 (DX11)
- Twitchmata 1.05b5

**Comment by tryallthethings** [comment]
Update: Over the course of 4.5 hours of stream today, I've seen the same error 6 times. And from what I could see from the logs, all the errors happened for gifted subs.

**Comment by pilky** [comment]
@tryallthethings As I suspected, this was to do with anonymous gifters. It should be fixed in the main branch

**Comment by tryallthethings** [comment]
Great, thank you! Will "test" it in the next stream. How do you test these kinds of things? Just ask someone to gift a sub to you, or is there a way to emulate them?

**Comment by pilky** [comment]
I've added a debug method to emulate an anonymous gift sub
